[package]
name = "wasmsand-coreutils"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cat"
path = "src/bin/cat.rs"

[[bin]]
name = "echo"
path = "src/bin/echo.rs"

[[bin]]
name = "head"
path = "src/bin/head.rs"

[[bin]]
name = "tail"
path = "src/bin/tail.rs"

[[bin]]
name = "wc"
path = "src/bin/wc.rs"

[[bin]]
name = "sort"
path = "src/bin/sort.rs"

[[bin]]
name = "uniq"
path = "src/bin/uniq.rs"

[[bin]]
name = "grep"
path = "src/bin/grep.rs"

[[bin]]
name = "ls"
path = "src/bin/ls.rs"

[[bin]]
name = "mkdir"
path = "src/bin/mkdir.rs"

[[bin]]
name = "rm"
path = "src/bin/rm.rs"

[[bin]]
name = "cp"
path = "src/bin/cp.rs"

[[bin]]
name = "mv"
path = "src/bin/mv.rs"

[[bin]]
name = "touch"
path = "src/bin/touch.rs"

[[bin]]
name = "tee"
path = "src/bin/tee.rs"

[[bin]]
name = "tr"
path = "src/bin/tr.rs"

[[bin]]
name = "cut"
path = "src/bin/cut.rs"

[[bin]]
name = "basename"
path = "src/bin/basename.rs"

[[bin]]
name = "dirname"
path = "src/bin/dirname.rs"

[[bin]]
name = "env"
path = "src/bin/env.rs"

[[bin]]
name = "printf"
path = "src/bin/printf.rs"

[[bin]]
name = "find"
path = "src/bin/find.rs"

[[bin]]
name = "sed"
path = "src/bin/sed.rs"

[[bin]]
name = "awk"
path = "src/bin/awk.rs"

[[bin]]
name = "jq"
path = "src/bin/jq.rs"

[[bin]]
name = "uname"
path = "src/bin/uname.rs"

[[bin]]
name = "whoami"
path = "src/bin/whoami.rs"

[[bin]]
name = "id"
path = "src/bin/id.rs"

[[bin]]
name = "printenv"
path = "src/bin/printenv.rs"

[[bin]]
name = "yes"
path = "src/bin/yes.rs"

[[bin]]
name = "rmdir"
path = "src/bin/rmdir.rs"

[[bin]]
name = "sleep"
path = "src/bin/sleep.rs"

[[bin]]
name = "seq"
path = "src/bin/seq.rs"

[[bin]]
name = "ln"
path = "src/bin/ln.rs"

[[bin]]
name = "readlink"
path = "src/bin/readlink.rs"

[[bin]]
name = "realpath"
path = "src/bin/realpath.rs"

[[bin]]
name = "mktemp"
path = "src/bin/mktemp.rs"

[[bin]]
name = "tac"
path = "src/bin/tac.rs"

[[bin]]
name = "xargs"
path = "src/bin/xargs.rs"

[[bin]]
name = "expr"
path = "src/bin/expr.rs"

[[bin]]
name = "diff"
path = "src/bin/diff.rs"

[[bin]]
name = "du"
path = "src/bin/du.rs"

[[bin]]
name = "df"
path = "src/bin/df.rs"

[[bin]]
name = "gzip"
path = "src/bin/gzip.rs"

[[bin]]
name = "tar"
path = "src/bin/tar.rs"

[[bin]]
name = "dc"
path = "src/bin/dc.rs"

[[bin]]
name = "bc"
path = "src/bin/bc.rs"

[[bin]]
name = "hostname"
path = "src/bin/hostname.rs"

[[bin]]
name = "base64"
path = "src/bin/base64.rs"

[[bin]]
name = "sha256sum"
path = "src/bin/sha256sum.rs"

[[bin]]
name = "md5sum"
path = "src/bin/md5sum.rs"

[[bin]]
name = "stat"
path = "src/bin/stat.rs"

[[bin]]
name = "xxd"
path = "src/bin/xxd.rs"

[[bin]]
name = "rev"
path = "src/bin/rev.rs"

[[bin]]
name = "nproc"
path = "src/bin/nproc.rs"

[dependencies]
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
tar = "0.4"
