[package]
name = "sqlite3-native"
version = "0.1.0"
edition = "2021"

[dependencies]
rustpython-vm = { git = "https://github.com/RustPython/RustPython", rev = "f9ca63893", default-features = false }
rustpython-derive = { git = "https://github.com/RustPython/RustPython", rev = "f9ca63893" }

[build-dependencies]
cc = "1"
